CRM_schedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls')),
    path('', include('users.urls')),
    path('captcha/', include('captcha.urls')),
]

schedule/urls.py
from django.urls import path

from schedule import views

app_name = 'schedule'

urlpatterns = [
    path('', views.display_schedule, name='schedule'),
    path('calendar/', views.show_calendar, name='calendar'),
    path('week/<int:pk>', views.show_detail, name='event_detail'),
    path('week/', views.week_schedule, name='week_schedule'),
    path('scheduleedit/<int:pk>', views.edit_schedule, name='edit_schedule'),
    path('daylist/<str:date>', views.show_events_ofday, name='day_events'),
    path('schedule_add/', views.add_schedule_line, name='schedule_add'),
    path('schedule_delete/<int:pk>', views.delete_schedule_line, name='delete_schedule_line'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import CreateUserView, view_profile, profile_edit, change_password

app_name = 'users'

urlpatterns = [
    path('reg/', CreateUserView.as_view(), name='registration'),
    path('login/',
         LoginView.as_view(template_name='users/login.html', success_url='{% url "users:profile" %}',
                           redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/change_password/', change_password, name='change_password'),
    path('profile/<int:id>/edit/', profile_edit, name='edit_profile'),
    path('profile/', view_profile, name='profile'),
]

schedule/models.py
from django.db import models


class Events(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование события')
    note = models.TextField(verbose_name='Примечание', blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Событие'
        verbose_name_plural = 'События'

    def __str__(self):
        return self.name


class EventTime(models.Model):
    start = models.TimeField(verbose_name='Время начала')
    end = models.TimeField(verbose_name='Время окончания', blank=True, null=True)
    note = models.TextField(verbose_name='Примечание', blank=True, null=True)

    class Meta:
        ordering = ('start',)
        verbose_name = 'Период события'
        verbose_name_plural = 'Временные интервалы событий'

    def __str__(self):
        return f'{self.start.strftime("%H:%M")} - {self.end.strftime("%H:%M")}'


class Teachers(models.Model):
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия', db_index=True)
    patronymic = models.CharField(max_length=255, verbose_name='Отчество', blank=True, null=True)
    photo = models.ImageField(verbose_name='Фото', blank=True, null=True)
    bio = models.TextField(verbose_name='О преподавателе', blank=True, null=True)

    class Meta:
        ordering = ('last_name', 'first_name',)
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Groups(models.Model):
    gr_num = models.CharField(max_length=255, verbose_name='Номер группы')
    course = models.ForeignKey('Courses', on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teachers, on_delete=models.DO_NOTHING, blank=True, null=True)
    start_date = models.DateField(verbose_name='Дата начала группы')
    end_date = models.DateField(verbose_name='Дата окончания группы')
    group_status = models.CharField(max_length=10, verbose_name='Статус группы', blank=True, null=True)
    person_cost = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Стоимость обучения 1 человека', blank=True, null=True)
    note = models.TextField(verbose_name='Примечание', blank=True, null=True)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return f'{self.gr_num} - {self.course.name}'


class Courses(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование курса')
    duration = models.DecimalField(verbose_name='Длительность курса', max_digits=3, decimal_places=1, blank=True,
                                   null=True)
    note = models.TextField(verbose_name='Примечание', blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    def __str__(self):
        return self.name


class Rooms(models.Model):
    room_num = models.CharField(max_length=255, verbose_name='Номер/наименование аудитории')
    note = models.TextField(verbose_name='Примечание', blank=True, null=True)

    class Meta:
        verbose_name = 'Аудитория'
        verbose_name_plural = 'Аудитории'

    def __str__(self):
        return self.room_num


class Schedule(models.Model):
    group = models.ForeignKey(Groups, on_delete=models.CASCADE, verbose_name='Группа', blank=True, null=True,
                              default=None)
    event = models.ForeignKey(Events, on_delete=models.CASCADE, verbose_name='Событие')
    event_time = models.ForeignKey(EventTime, on_delete=models.DO_NOTHING, blank=True, null=True,
                                   verbose_name='Время события', related_name='time')
    event_date = models.DateField(verbose_name='Дата события')
    teacher = models.ForeignKey(Teachers, on_delete=models.DO_NOTHING, blank=True, null=True,
                                verbose_name='Преподаватель')
    room = models.ForeignKey(Rooms, on_delete=models.DO_NOTHING, blank=True, null=True,
                             verbose_name='Аудитория')
    note = models.TextField(verbose_name='Примечание', blank=True, null=True)

    class Meta:
        verbose_name = 'Событие в расписании'
        verbose_name_plural = 'Раписание'
        unique_together = [['event_time', 'teacher', 'event_date'], ['event_time', 'room', 'event_date'],
                           ['event_time', 'group', 'event_date']]

    def __str__(self):
        return f'{self.group}, {self.event}, {self.event_time}, {self.event_date}, {self.room}'

    def short_name(self):
        return f'{self.event}, {self.group}, {self.teacher}, ауд. {self.room}'

schedule/forms.py
from django import forms

from schedule.models import Schedule


class TeacherFilter(forms.ModelForm):
    event_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}), label="Дата", required=False)

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if user.is_authenticated and (user.student_id or user.teacher_id):
            self.fields['group'].queryset = self.fields['group'].queryset.filter(students=user)

    class Meta:
        model = Schedule
        fields = ['teacher', 'room', 'group', 'event_date']


class ScheduleEdit(forms.ModelForm):
    event_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}), label="Дата")

    def clean(self):
        cleaned_data = super().clean()
        event_date = cleaned_data.get("event_date")
        group = cleaned_data.get("group")
        if event_date > group.end_date or event_date < group.start_date:
            msg = "Дата события не соответствует периоду обучения группы."
            self.add_error('event_date', msg)

    class Meta:
        model = Schedule
        fields = ['event', 'event_date', 'event_time', 'room', 'group', 'teacher', 'note']

schedule/views.py
import calendar
import datetime

import pandas as pd
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Max, Min
from django.shortcuts import render, get_object_or_404, redirect

from .forms import TeacherFilter, ScheduleEdit
from .models import Schedule, EventTime, Groups, Rooms


def display_schedule(request):
    form = TeacherFilter(request.user, request.GET)
    schedule_lines = Schedule.objects.all()
    if not schedule_lines:
        return render(request, 'schedule/empty_schedule_form.html')
    # отображаются для студента и преподавателя даты только их групп, для менеджера, директора и администратора -
    # все возможные даты всех групп
    if request.user.is_authenticated:
        if request.user.student_id:
            # aggregate выбирает данные напрямую из БД без формирования queryset
            start_end = Groups.objects.filter(students=request.user).aggregate(Max('end_date'), Min('start_date'))
            dates = [single_date for single_date in
                     pd.date_range(start_end.get('start_date__min'), start_end.get('end_date__max'))]
            schedule_lines = Schedule.objects.filter(
                event_date__range=(start_end.get('start_date__min'), start_end.get('end_date__max')),
                group__in=Groups.objects.filter(students=request.user))
        elif request.user.teacher_id:
            start_end = Groups.objects.filter(teacher=request.user).aggregate(Max('end_date'), Min('start_date'))
            dates = [single_date for single_date in
                     pd.date_range(start_end.get('start_date__min'), start_end.get('end_date__max'))]
            schedule_lines = Schedule.objects.filter(
                event_date__range=(start_end.get('start_date__min'), start_end.get('end_date__max')),
                group__in=Groups.objects.filter(teacher=request.user))
        else:
            start_end = Groups.objects.all().aggregate(Max('end_date'), Min('start_date'))
            dates = [single_date for single_date in
                     pd.date_range(start_end.get('start_date__min'), start_end.get('end_date__max'))]
    else:
        start_end = schedule_lines.aggregate(Max('event_date'), Min('event_date'))
        dates = [single_date for single_date in
                 pd.date_range(start_end.get('event_date__min'), start_end.get('event_date__max'))]

    if form.is_valid():
        schedule_lines = schedule_lines.filter(**{k: v for k, v in form.cleaned_data.items() if v})
        if request.GET.get('event_date'):
            dates = [datetime.datetime.strptime(request.GET.get('event_date'), '%Y-%m-%d').date()]
        elif request.GET:
            start_end = schedule_lines.aggregate(Max('event_date'), Min('event_date'))
            dates = [single_date for single_date in
                     pd.date_range(start_end.get('event_date__min'), start_end.get('event_date__max'))]

    if request.user.is_authenticated and not (request.user.student_id or request.user.teacher_id):
        times = EventTime.objects.all()
        if request.GET.get('room'):
            rooms = Rooms.objects.filter(id__in=schedule_lines.values_list('room', flat=True))
        else:
            rooms = Rooms.objects.all()
    else:
        times = EventTime.objects.filter(id__in=schedule_lines.values_list('event_time', flat=True))
        rooms = Rooms.objects.filter(id__in=schedule_lines.values_list('room', flat=True))
    time_dict = {
        room: {
            time: {
                k: schedule_lines.filter(event_time=time, event_date=k, room=room) for k in dates
            } for time in times
        } for room in rooms
    }
    return render(request, 'schedule/schedule_form.html', locals())


def show_calendar(request):
    today = datetime.date.today()
    days = list(calendar.Calendar(firstweekday=0).itermonthdates(today.year, today.month))
    schedule_dates = [i[0] for i in list(Schedule.objects.values_list('event_date'))]
    return render(request, 'schedule/calender.html', locals())


def week_schedule(request):
    form = TeacherFilter(request.user, request.GET)
    today = datetime.datetime.today()
    week_num = request.GET.get('week', default=today.isocalendar()[1])
    d = f'{today.year}-{week_num}'
    dates_of_week = [datetime.datetime.strptime(f'{d}-{i}', '%G-%V-%u').date() for i in range(1, 8)]
    schedule_lines = Schedule.objects.filter(event_date__in=dates_of_week)

    if form.is_valid():
        schedule_lines = schedule_lines.filter(**{k: v for k, v in form.cleaned_data.items() if v})
        if request.GET.get('event_date'):
            dates = [datetime.datetime.strptime(request.GET.get('event_date'), '%Y-%m-%d').date()]

    times = EventTime.objects.filter(id__in=schedule_lines.values_list('event_time', flat=True))
    rooms = Rooms.objects.filter(id__in=schedule_lines.values_list('room', flat=True))
    time_dict = {
        room: {time: {k: schedule_lines.filter(event_time=time, event_date__iso_week_day=k, room=room) for k in
                      range(1, 8)}
               for time in times} for room in rooms}
    return render(request, 'schedule/week_schedule.html', locals())


def show_detail(request, pk):
    info = get_object_or_404(Schedule, id=pk)
    return render(request, 'schedule/schedule_detail.html', locals())


@login_required
def edit_schedule(request, pk):
    schedule_info = get_object_or_404(Schedule, id=pk)
    if request.method == "POST":
        form = ScheduleEdit(request.POST, instance=schedule_info)
        if form.is_valid():
            schedule_info = form.save()
            return redirect('schedule:event_detail', pk=pk)
    else:
        form = ScheduleEdit(instance=schedule_info)
    return render(request, 'schedule/edit_schedule.html', locals())


def show_events_ofday(request, date):
    schedule_info = Schedule.objects.filter(event_date=date)
    return render(request, 'schedule/day_list.html', locals())


@login_required
@permission_required('add_schedule', raise_exception=True)
def add_schedule_line(request):
    if request.GET:
        form = ScheduleEdit(initial={'event_date': request.GET.get('date'), 'event_time': request.GET.get('time'),
                                     'room': request.GET.get('room')})
    else:
        form = ScheduleEdit()
    if request.method == 'POST':
        form = ScheduleEdit(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            Schedule.objects.create(group=cleaned_data['group'],
                                    event=cleaned_data['event'],
                                    event_time=cleaned_data['event_time'],
                                    event_date=cleaned_data['event_date'],
                                    teacher=cleaned_data['teacher'],
                                    room=cleaned_data['room'],
                                    note=cleaned_data['note'])
            return redirect('schedule:schedule')
    return render(request, 'schedule/add_line.html', locals())


def book_room(request):
    rooms = Schedule.objects.all()
    return render(request, 'schedule/book_room.html', locals())


@login_required
def delete_schedule_line(request, pk):
    schedule_line = get_object_or_404(Schedule, pk=pk)
    schedule_line.delete()
    messages.add_message(request, messages.SUCCESS, 'Запись удалена')
    return redirect('schedule:schedule')

templates/schedule/add_defined_event.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

templates/schedule/add_line.html
{% extends "schedule/../base.html" %}
{% load bootstrap4 %}

{% block title %}Занятия на {{ schedule_info.0.event_date }}{% endblock %}

{% block content %}
<h2 class="row justify-content-around">Добавление записи расписания</h2><br>
<div class="row justify-content-around">

        <div class="col-sm-6 col-lg-5">
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-success">Добавить</button>
    <a class="btn btn-dark" href="{% url 'schedule:schedule' %}">Назад</a>
<!--    <button class="btn btn-warning" onclick="redirect()">Сохранить и добавить еще</button>-->
</form>



        </div>
</div>
{% endblock %}

<!--<script>-->
<!--   var redirect = function(){-->
<!--   document.location.href="http://127.0.0.1:8000/schedule_add/"-->
<!--}-->
<!--</script>-->

templates/schedule/calender.html
{% extends "schedule/../base.html" %}

{% block title %}Календарь{% endblock %}

{% block content %}
    <h3 class="text-center">Календарь на текущий месяц</h3>
    <div class="container">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>№ недели</th>
                <th>Понедельник</th>
                <th>Вторник</th>
                <th>Среда</th>
                <th>Четверг</th>
                <th>Пятница</th>
                <th>Суббота</th>
                <th>Воскресенье</th>
            </tr>
            </thead>
            <tbody>

            {% for day in days %}
                {% if forloop.counter|add:"-1"|divisibleby:'7' %}
                    <tr>
                    <td>
                        {#                Отображается номер календарной недели, потом можно будет высчитывать номер учебной недели от даты начала курса#}
                        <a href="{% url 'schedule:week_schedule' %}?week={{ day.isocalendar.1 }}"
                           title="Посмотреть расписание на неделю">{{ day.isocalendar.1 }}</a>
                    </td>
                {% endif %}
            <td>{{ day|date:"d.m" }}<br>
                {% if day in schedule_dates %}
                    <a href="{% url 'schedule:day_events' date=day %}" title="Просмотр занятий на день">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-check" viewBox="0 0 16 16">
                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                        </svg>
                    </a>{% endif %}</td>
            {% if forloop.counter|divisibleby:'7' %}
                </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-dark" href=" {% url 'schedule:schedule' %}">Назад</a>
    </div>
{% endblock %}

templates/schedule/day_list.html
{% extends "schedule/../base.html" %}

{% block title %}Занятия на {{ schedule_info.0.event_date }}{% endblock %}

{% block content %}
<h3>Занятия на {{ schedule_info.0.event_date }}</h3>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>№</th>
        <th>Название</th>
        <th>Время</th>
        <th>Аудитория</th>
        <th>Преподаватель</th>
        <th>Предмет</th>
        <th>Примечание</th>
    </tr>
    </thead>
    <tbody>
    {% for i in schedule_info %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ i.event }}</td>
        <td>{{ i.event_time }}</td>
        <td>{{ i.room }}</td>
        <td>{{ i.teacher }}</td>
        <td>{{ i.group.course }}</td>
        <td>{{ i.note }}</td>
    </tr>
    {% endfor %}
    </tbody>


</table>
<a class="btn btn-dark" href=" {% url 'schedule:calendar' %}">Назад</a>
{% endblock %}

templates/schedule/edit_schedule.html
{% extends "schedule/../base.html" %}
{% load bootstrap4 %}

{% block title %}Редактирование{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-dark">Сохранить</button>
            <a class="btn btn-danger" href="{% url 'schedule:delete_schedule_line' pk=pk %}">Удалить</a>
            <a class="btn btn-secondary" href=" {% url 'schedule:event_detail' pk=pk %}">Назад</a>


        </form>
    </div>
{% endblock %}

templates/schedule/empty_schedule_form.html
{% extends "schedule/../base.html" %}
{% load bootstrap4 %}

{% block title %}Все расписание{% endblock %}

{% block content %}

<div class="container">
    {% if request.user.is_staff %}
    <div style="margin: 10px;">
        <a class="btn btn-success" href=" {% url 'schedule:schedule_add' %}">Добавить запись</a>
    </div>
    {% endif %}
    <div class="empty_page_text">
        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-emoji-frown"
             viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
        </svg>
        Упс.. Похоже, учиться пока рано. Расписание еще не составлено.
    </div>
</div>
{% endblock %}

templates/schedule/schedule_detail.html
{% extends "schedule/../base.html" %}

{% block title %}{{ info }}{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th colspan="2">{{ info.event }}</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Дата:</td>
                <td>{{ info.event_date|date:"d.m.Y" }}</td>
            </tr>
            <tr>
                <td>Время:</td>
                <td>{{ info.event_time }}</td>
            </tr>
            <tr>
                <td>Аудитория:</td>
                <td>{{ info.room }}</td>
            </tr>
            <tr>
                <td>Преподаватель:</td>
                <td>{{ info.teacher }}</td>
            </tr>
            <tr>
                <td>Группа:</td>
                <td>{{ info.group }}</td>
            </tr>
            <tr>
                <td>Курс</td>
                <td>{{ info.group.course }}</td>
            </tr>
            {% if info.note %}
                <tr>
                    <td>Примечание</td>
                    <td>{{ info.note }}</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    {% if user.is_staff %}
        <a class="btn btn-secondary" href=" {% url 'schedule:edit_schedule' pk=pk %}">Редактировать</a>
        <a class="btn btn-danger" href="{% url 'schedule:delete_schedule_line' pk=pk %}">Удалить</a>
    {% endif %}
        <a class="btn btn-dark" href=" {% url 'schedule:schedule' %}">Назад</a>
    </div>
{% endblock %}

templates/schedule/schedule_form.html
{% extends "schedule/../base.html" %}
{% load bootstrap4 %}

{% block title %}Все расписание{% endblock %}

{% block content %}

  <div class="container">
    {% if request.user.is_staff %}
      <div style="margin: 10px;">
        <a class="btn btn-success" href=" {% url 'schedule:schedule_add' %}">Добавить запись</a>
      </div>
    {% endif %}
    <form style="margin: 20px 0; text-align: center;">
      {{ form }}
      <button class="btn btn-light">Выбрать</button>
    </form>

    <div style="position: relative;">
      <div style="overflow-x: auto; margin-left: 150px">

        <table class="table table-bordered">
          <thead>
          <tr>
            <th rowspan="" style="position: absolute; border: 0; left: -150px; margin-top: -1px; min-width: 150px; ">
              Аудитория
            </th>
            <th style="position: absolute; border: 0; left: 0; margin-top: -1px; min-width: 150px; ">Время
              занятий
            </th>
            {% for date in dates %}
              <th>{{ date|date:"l" }}</th>
            {% endfor %}
          </tr>
          </thead>
          <tbody>
          <tr>
            <td style="position: absolute; border: 0; left: 0; margin-top: -1px; min-width: 150px; ">&nbsp;
            </td>
            {% for date in dates %}
              <td>{{ date|date:"d.m" }}</td>
            {% endfor %}
          </tr>
          {% for room, schedule_time_dict in time_dict.items %}

            {% for time, schedule_lines_dict in schedule_time_dict.items %}
              <tr>
                {% ifchanged %}
                  <td style="position: absolute; border: 0; border-top: inherit; left: -150px; margin-top: -1px; min-width: 150px; ">{{ room }}</td>
                {% endifchanged %}
                <td style="position: absolute; border: 0; {% if forloop.first %} border-top: inherit;{% endif %}  left: 0; margin-top: -1px; min-width: 150px; ">{{ time }}</td>
                {% for date, schedule_lines in schedule_lines_dict.items %}
                  {% if schedule_lines.exists %}
                    <td>
                      <ul>
                        {% for schedule_line in schedule_lines %}

                          <li>
                            <a href="{% url 'schedule:event_detail' schedule_line.id %}">{{ schedule_line.short_name }}</a>
                          </li>
                          {% if request.user.is_staff %}
                            <a class="text-dark"
                               href="{% url 'schedule:schedule_add' %}?date={{ date|date:'Y-m-d' }}&time={{ time.id }}&room={{ room.id }}">
                              <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor"
                                   class="bi bi-plus-lg" viewBox="0 0 16 16">
                                <path
                                    d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                              </svg>
                              Добавить событие
                            </a>
                          {% endif %}
                        {% endfor %}
                      </ul>
                    </td>

                  {% else %}
                    {% if user.is_staff %}
                      <td><a class="text-dark"
                             href="{% url 'schedule:schedule_add' %}?date={{ date|date:'Y-m-d' }}&time={{ time.id }}&room={{ room.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor"
                             class="bi bi-plus-lg" viewBox="0 0 16 16">
                          <path
                              d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                        </svg>
                      </a></td>
                    {% else %}
                      <td>---</td>
                    {% endif %}
                  {% endif %}
                {% endfor %}
              </tr>
            {% endfor %}
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}