CRM_schedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls')),
    path('', include('users.urls')),
    path('captcha/', include('captcha.urls')),
]

schedule/urls.py
from django.urls import path

from schedule import views

app_name = 'schedule'

urlpatterns = [
    path('', views.display_schedule, name='schedule'),
    path('calendar/', views.show_calendar, name='calendar'),
    path('week/<int:pk>', views.show_detail, name='event_detail'),
    path('week/', views.week_schedule, name='week_schedule'),
    path('scheduleedit/<int:pk>', views.edit_schedule, name='edit_schedule'),
    path('daylist/<str:date>', views.show_events_ofday, name='day_events'),
    path('schedule_add/', views.add_schedule_line, name='schedule_add'),
    path('schedule_delete/<int:pk>', views.delete_schedule_line, name='delete_schedule_line'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import CreateUserView, view_profile, profile_edit, change_password

app_name = 'users'

urlpatterns = [
    path('reg/', CreateUserView.as_view(), name='registration'),
    path('login/',
         LoginView.as_view(template_name='users/login.html', success_url='{% url "users:profile" %}',
                           redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/change_password/', change_password, name='change_password'),
    path('profile/<int:id>/edit/', profile_edit, name='edit_profile'),
    path('profile/', view_profile, name='profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">

    <title>{% block title %}Расписание{% endblock %}</title>

    {% block style %}{% endblock %}
</head>

<body class="back">
<header class="header">
    <a href="/" class="logo">
        Scedule app
    </a>
    <div class="header__buttons">
        {% if user.is_authenticated %}
            <a class="btn btn-light"
               href="{%  url 'users:profile' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd"
                          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
                {{ user }}</a>
            <a class="btn btn-light"
               href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="btn btn-light"
               href="{% url 'users:login' %}">Вход</a>
            <a class="btn btn-light" href="{% url 'users:registration' %}">Регистрация</a>
        {% endif %}
    </div>
</header>

<div class="btn-group" role="group" aria-label="Schedule_nav">
    <a class="btn {% if request.get_raw_uri == 'http://127.0.0.1:8000/schedule/' %} btn-secondary{% else %}btn-light{% endif %}"
       href="{% url 'schedule:schedule' %}">Все расписание</a>
    <a class="btn {% if request.get_raw_uri == 'http://127.0.0.1:8000/schedule/calendar/' %} btn-secondary{% else %}btn-light{% endif %}"
       href="{% url 'schedule:calendar' %}">Календарь на месяц</a>
    <a class="btn {% if request.get_raw_uri == 'http://127.0.0.1:8000/schedule/week/' %} btn-secondary{% else %}btn-light{% endif %}"
       href="{% url 'schedule:week_schedule' %}">Расписание на неделю</a>
</div>

{% block content %}

{% endblock %}
</body>
</html>