CRM_schedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls')),
    path('', include('users.urls')),
    path('captcha/', include('captcha.urls')),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import CreateUserView, view_profile, profile_edit, change_password

app_name = 'users'

urlpatterns = [
    path('reg/', CreateUserView.as_view(), name='registration'),
    path('login/',
         LoginView.as_view(template_name='users/login.html', success_url='{% url "users:profile" %}',
                           redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/change_password/', change_password, name='change_password'),
    path('profile/<int:id>/edit/', profile_edit, name='edit_profile'),
    path('profile/', view_profile, name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from schedule.models import Teachers, Groups


class User(AbstractUser):
    teacher = models.ForeignKey(Teachers, on_delete=models.DO_NOTHING, blank=True, null=True)
    student = models.ForeignKey('Students', on_delete=models.DO_NOTHING, blank=True, null=True)
    profile_photos = models.ForeignKey('ProfilePhotos', on_delete=models.CASCADE, verbose_name='Фото профиля',
                                       blank=True, null=True)
    age = models.CharField(max_length=3, blank=True, null=True, verbose_name='Возраст')
    birthday = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    city = models.CharField(max_length=100, verbose_name='Город')
    status_message = models.CharField(max_length=100, verbose_name='Статус')
    contacts = models.CharField('Номер телефона', max_length=255) #сделать связь
    address = models.TextField('Адрес', blank=True, null=True)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username


class ProfilePhotos(models.Model):
    profile_photo = models.ImageField(upload_to=f'profile_avatars/')

    class Meta:
        verbose_name = 'Фото профиля'
        verbose_name_plural = 'Фото профиля'


class Contacts(models.Model):
    phone = models.CharField('Номер телефона', max_length=255)
    email = models.EmailField('Электронная почта')

    class Meta:
        verbose_name = 'Контакты пользователя'
        verbose_name_plural = 'Контакты пользователей'


class Students(models.Model):
    name = models.CharField('Имя', max_length=255)
    surname = models.CharField('Фамилия', max_length=255)
    patronymic = models.CharField('Отчестсво', max_length=255, null=True, blank=True)
    group = models.ManyToManyField(Groups, related_name='group')

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

users/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.password_validation import validate_password
from django.forms import ModelForm

from users.models import User


class RegistrationForm(UserCreationForm):
    captcha = CaptchaField(label='Введите символы, изображенные на картинке')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'address']


class ProfileEdit(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'address']


class ChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(max_length=70, widget=forms.PasswordInput, label='Старый пароль')
    new_password1 = forms.CharField(max_length=70, widget=forms.PasswordInput, label='Новый пароль',
                                    validators=[validate_password])
    new_password2 = forms.CharField(max_length=70, widget=forms.PasswordInput, label='Повторите пароль')

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

users/views.py
from datetime import datetime, timedelta

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.core.mail import send_mail
from django.conf import settings

from users.forms import RegistrationForm, ProfileEdit, ChangePasswordForm
from users.models import User


class CreateUserView(CreateView):
    model = User
    template_name = 'users/registration.html'
    form_class = RegistrationForm

    def get_success_url(self):
        url = reverse('users:profile')
        return url


@login_required
def view_profile(request):
    user_info = User.objects.get(username=request.user.username)
    return render(request, 'users/profile.html', {'user_info': user_info})


@login_required
def profile_edit(request, id):
    user_info = get_object_or_404(User, pk=id)
    if request.method == "POST":
        form = ProfileEdit(request.POST, instance=user_info)
        if form.is_valid():
            user_info = form.save(commit=False)
            user_info.save()
            return redirect('authentication:profile')
    else:
        form = ProfileEdit(instance=user_info)
    return render(request, 'users/edit_profile.html', {'form': form, 'user_info': user_info})


@login_required
def change_password(request):
    user_info = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        passwords = request.POST
        user = request.user
        old_password = passwords['old_password']
        new_password1 = passwords['new_password1']
        new_password2 = passwords['new_password2']
        if check_password(old_password, user.password):
            if new_password1 == new_password2:
                user.set_password(new_password1)
                user.save()
                update_session_auth_hash(request, user)
                return redirect('users:profile')
            else:
                msg = "Повторенный пароль не соответствует исходному."
                form.add_error('new_password2', msg)
                context = {'form': form}
                return render(request, 'users/change_password.html', context)
        else:
            msg = "Введен неверный пароль."
            form.add_error('old_password', msg)
            if not new_password1 == new_password2:
                msg2 = "Повторенный пароль не соответствует исходному."
                form.add_error('new_password2', msg2)
                context = {'form': form}
                return render(request, 'users/change_password.html', context)
            context = {'form': form}
            return render(request, 'users/change_password.html', context)
    form = ChangePasswordForm()
    context = {'form': form, 'user_info': user_info}
    return render(request, 'users/change_password.html', context)


# def email(request, pk):
#     subject = 'Регистрация на сайте школы ITEC'
#     message = User.objects.filter(id=pk).first().first_name + ' ' + User.objects.filter(
#         id=pk).first().last_name + ', добро пожаловать на сайт школы ITEC!\n\nЖелаем успешного обучения!'
#     email_from = settings.EMAIL_HOST_USER
#     recipient_list = [User.objects.filter(id=pk).first().email]
#     send_mail(subject, message, email_from, recipient_list)
#     return redirect('users:profile')

templates/users/_profile_nav.html
<div class="bg-light">
    <div class="btn-group" role="group" aria-label="Basic example">
        {% if user_info.is_superuser %}
            <a
                    class="btn {% if active == 'received_orders' %} btn-secondary {% else %}btn-light{% endif %}"
                    href="{% url 'authentication:received_orders' %}">Поступившие заказы</a>
            {#    <a#}
            {#           class="btn {% if active == 'add_product' %} btn-secondary {% else %}btn-light{% endif %}"#}
            {#           href="{% url 'orders:add_product' %}">Добавление товаров</a>#}
        {% endif %}

        <a
                class="btn {% if active == 'info' %} btn-secondary {% else %}btn-light{% endif %}"
                href="
    {% url 'authentication:profile' %}">Профиль</a>
        <a
                class="btn {% if active == 'history' %} btn-secondary {% else %}btn-light{% endif %}"
                href="{% url 'orders:order_history' %}">История заказов</a>
    </div>
</div>

templates/users/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
    {% include 'authentication/_profile_nav.html' with active='info' %}
    <div class="row">
        <div class="col-sm-6 col-lg-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ error }}
                {% bootstrap_form form %}
                <button class="btn btn-dark">Сменить пароль</button>
                <a class="btn btn-secondary" href=" {% url 'authentication:profile'%}">Назад</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Редактировать{% endblock %}
{% block content %}
    {% include 'authentication/_profile_nav.html' with active='info' %}
    <div class="row">
        <div class="col-sm-6 col-lg-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ error }}
                {% bootstrap_form form %}
{#                <p><input id="messages" type="checkbox"> <label for="messages">Подписаться на нашу рассылку</label></p>#}
{#                <p>#}
                    <button class="btn btn-dark">Сохранить изменения</button>
                    <a class="btn btn-secondary" href=" {% url 'authentication:profile'%}">Назад</a>
                </p>
            </form>
        </div>
    </div>


{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Вход{% endblock %}
{% block content %}
    <div class="container ">

        <div class="row justify-content-around">
            <div class="col-sm-6 col-lg-5">
                <h3>Добро пожаловать!</h3>
                <br>
                <h5>Представьтесь, пожалуйста:</h5>
                <br>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ error }}
                    {% bootstrap_form form %}
                    <button class="btn btn-dark">Войти</button>
                    <input type="hidden" name="next" value="{% url 'users:profile' %}">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профиль{% endblock %}
{% block content %}
{#    {% include 'users/_profile_nav.html' with active='info' %}#}
    <div class="container">
        <div style="padding-top: 10px; padding-bottom: 10px;">
            <a class="btn btn-dark" href=" {% url 'users:edit_profile' id=user.id %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil"
                     viewBox="0 0 16 16">
                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                </svg>
                Редактировать профиль</a>
            <a class="btn btn-dark" href="{% url 'users:change_password' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-eraser-fill"
                     viewBox="0 0 16 16">
                    <path d="M8.086 2.207a2 2 0 0 1 2.828 0l3.879 3.879a2 2 0 0 1 0 2.828l-5.5 5.5A2 2 0 0 1 7.879 15H5.12a2 2 0 0 1-1.414-.586l-2.5-2.5a2 2 0 0 1 0-2.828l6.879-6.879zm.66 11.34L3.453 8.254 1.914 9.793a1 1 0 0 0 0 1.414l2.5 2.5a1 1 0 0 0 .707.293H7.88a1 1 0 0 0 .707-.293l.16-.16z"/>
                </svg>
                Сменить пароль</a>
        </div>
        <div class="col-sm-6">
            <table class="table table-striped">
                <tbody>
                <tr>
                    <th scope="row">Логин:</th>
                    <td>{{ user_info.username }}</td>
                </tr>
                <tr>
                    <th scope="row">Имя:</th>
                    <td>{{ user_info.first_name }} {{ user_info.last_name }}</td>
                </tr>
                <tr>
                    <th scope="row">E-mail:</th>
                    <td>{{ user_info.email }}</td>
                </tr>
                <tr>
                    <th scope="row">Телефон:</th>
                    <td>{{ user_info.phone }}</td>
                </tr>
                <tr>
                    <th scope="row">Адрес:</th>
                    <td>{{ user_info.address }}</td>
                </tr>
                </tbody>
            </table>
        </div>

        {#    <p>Логин: {{ user_info.username }}</p>#}
        {#    <p>Имя: {{ user_info.first_name }}</p>#}
        {#    <p>Фамилия: {{ user_info.last_name }}</p>#}
        {#    <p>E-mail: {{ user_info.email }}</p>#}
        {#    <p>Телефон: {{ user_info.phone }}</p>#}
        {#    <p>Адрес: {{ user_info.address }}</p>#}
        <a type="button" class="btn btn-secondary" href="/">Вернуться на главную</a>
    </div>


{% endblock %}

templates/users/registration.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Регистрация{% endblock %}
{% block content %}
    <div class="container">

        <div class="row justify-content-around">
            <div class="col-sm-7 col-lg-7">
                <h4>Добро пожаловать!</h4>
                <br>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ error }}
                    {% bootstrap_form form %}
                    <p><i>*После регистрации на Вашу электронную почту будет отправлено письмо с подтвержением.</i></p>
                    <button class="btn btn-success">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-envelope-fill" viewBox="0 0 16 16">
                            <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                        </svg>
                        Зарегистрироваться
                    </button>
                </form>


{% endblock %}